image: java:latest

before_script:
    - apt-get update && apt-get install make
    - test -f /opt/compiler.jar || { curl -L http://dl.google.com/closure-compiler/compiler-latest.tar.gz | tar -xzf - -C /opt; }
    - echo -e '#!/bin/sh\n"$JAVA_HOME/bin/java" -jar /opt/compiler.jar $@' > /usr/local/bin/closure

stages:
    - build

minify:
    stage: build
    script:
        - make && rm -rf /out/berrytweaks/min && cp -r min /out/berrytweaks/
    cache:
        paths:
            - /opt/compiler.jar
    artifacts:
        paths:
            - ./*.js
            - ./*.html
            - api/*.py
            - api/*.php
            - min/css
            - min/js

