image: java:latest

stages:
    - build

minify:
    stage: build
    before_script:
        - test -f /opt/compiler.jar || { curl -L http://dl.google.com/closure-compiler/compiler-latest.tar.gz | tar -xzf - -C /opt; }
        - echo -e '#!/bin/sh\n"$JAVA_HOME/bin/java" -jar /opt/compiler.jar $@' > /usr/local/bin/closure
    script:
        - cd min
        - ./build.sh
    cache:
        paths:
            - /opt/compiler.jar
    artifacts:
        paths:
            - ./*.js
            - ./*.html
            - api/*.py
            - api/*.php
            - min/css
            - min/js

